apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenml-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zenml-gateway
  template:
    metadata:
      labels:
        app: zenml-gateway
    spec:
      containers:
        - name: gateway
          image: zenml-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000