export const AUDIT_ACTIONS = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ACCESS: "ACCESS",
};

export const AUDIT_RESOURCES = {
  WORKSPACE: "WORKSPACE",
  USER: "USER",
  SERVICE_ACCOUNT: "SERVICE_ACCOUNT",
  API_KEY: "API_KEY",
};
